// AUTO-GENERATED by scripts/generate-db-types.ts - do not edit by hand.
// Regenerate after changing migrations: npm run db:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      audit_log: {
        Row: {
          id: number
          occurred_at: string
          user_id: string | null
          user_email: string | null
          action: string
          entity_type: string
          entity_id: string | null
          details: Json
          old_values: Json | null
          new_values: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          occurred_at?: string
          user_id?: string | null
          user_email?: string | null
          action: string
          entity_type: string
          entity_id?: string | null
          details?: Json
          old_values?: Json | null
          new_values?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          occurred_at?: string
          user_id?: string | null
          user_email?: string | null
          action?: string
          entity_type?: string
          entity_id?: string | null
          details?: Json
          old_values?: Json | null
          new_values?: Json | null
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      categories: {
        Row: {
          id: string
          code: string
          name: string
          description: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          code: string
          name: string
          description?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          code?: string
          name?: string
          description?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      customers: {
        Row: {
          id: string
          code: string
          name: string
          customer_type: string
          contact_name: string | null
          email: string | null
          phone: string | null
          address_line: string | null
          city: string | null
          country: string
          tax_id: string | null
          credit_limit: number
          payment_terms_days: number
          notes: string | null
          is_active: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          code: string
          name: string
          customer_type?: string
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          address_line?: string | null
          city?: string | null
          country?: string
          tax_id?: string | null
          credit_limit?: number
          payment_terms_days?: number
          notes?: string | null
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          code?: string
          name?: string
          customer_type?: string
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          address_line?: string | null
          city?: string | null
          country?: string
          tax_id?: string | null
          credit_limit?: number
          payment_terms_days?: number
          notes?: string | null
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "customers_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      goods_receipt_items: {
        Row: {
          id: string
          goods_receipt_id: string
          purchase_order_item_id: string
          product_id: string
          quantity_received: number
          unit_cost: number
          stock_movement_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          goods_receipt_id: string
          purchase_order_item_id: string
          product_id: string
          quantity_received: number
          unit_cost: number
          stock_movement_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          goods_receipt_id?: string
          purchase_order_item_id?: string
          product_id?: string
          quantity_received?: number
          unit_cost?: number
          stock_movement_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "goods_receipt_items_goods_receipt_id_fkey"
            columns: ["goods_receipt_id"]
            isOneToOne: false
            referencedRelation: "goods_receipts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goods_receipt_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goods_receipt_items_purchase_order_item_id_fkey"
            columns: ["purchase_order_item_id"]
            isOneToOne: false
            referencedRelation: "purchase_order_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goods_receipt_items_stock_movement_id_fkey"
            columns: ["stock_movement_id"]
            isOneToOne: true
            referencedRelation: "stock_movements"
            referencedColumns: ["id"]
          },
        ]
      }
      goods_receipts: {
        Row: {
          id: string
          receipt_number: string
          purchase_order_id: string
          warehouse_id: string
          received_by: string | null
          received_at: string
          notes: string | null
          created_at: string
          updated_at: string
          reversed_at: string | null
          reversed_by: string | null
          reversal_reason: string | null
        }
        Insert: {
          id?: string
          receipt_number?: string
          purchase_order_id: string
          warehouse_id: string
          received_by?: string | null
          received_at?: string
          notes?: string | null
          created_at?: string
          updated_at?: string
          reversed_at?: string | null
          reversed_by?: string | null
          reversal_reason?: string | null
        }
        Update: {
          id?: string
          receipt_number?: string
          purchase_order_id?: string
          warehouse_id?: string
          received_by?: string | null
          received_at?: string
          notes?: string | null
          created_at?: string
          updated_at?: string
          reversed_at?: string | null
          reversed_by?: string | null
          reversal_reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "goods_receipts_purchase_order_id_fkey"
            columns: ["purchase_order_id"]
            isOneToOne: false
            referencedRelation: "purchase_orders"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goods_receipts_received_by_fkey"
            columns: ["received_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goods_receipts_reversed_by_fkey"
            columns: ["reversed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "goods_receipts_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      inventory: {
        Row: {
          id: string
          product_id: string
          warehouse_id: string
          quantity: number
          bin_location: string | null
          last_movement_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          product_id: string
          warehouse_id: string
          quantity?: number
          bin_location?: string | null
          last_movement_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          warehouse_id?: string
          quantity?: number
          bin_location?: string | null
          last_movement_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "inventory_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "inventory_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      products: {
        Row: {
          id: string
          sku: string
          name: string
          description: string | null
          category_id: string
          unit_of_measure: string
          barcode: string | null
          cost_price: number
          sale_price: number
          min_stock_level: number
          reorder_quantity: number
          is_active: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          sku: string
          name: string
          description?: string | null
          category_id: string
          unit_of_measure?: string
          barcode?: string | null
          cost_price?: number
          sale_price?: number
          min_stock_level?: number
          reorder_quantity?: number
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          sku?: string
          name?: string
          description?: string | null
          category_id?: string
          unit_of_measure?: string
          barcode?: string | null
          cost_price?: number
          sale_price?: number
          min_stock_level?: number
          reorder_quantity?: number
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "products_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "categories"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "products_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          role_id: number
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string
          role_id: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string
          role_id?: number
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_role_id_fkey"
            columns: ["role_id"]
            isOneToOne: false
            referencedRelation: "roles"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_order_items: {
        Row: {
          id: string
          purchase_order_id: string
          line_number: number
          product_id: string
          quantity_ordered: number
          quantity_received: number
          unit_cost: number
          line_total: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          purchase_order_id: string
          line_number: number
          product_id: string
          quantity_ordered: number
          quantity_received?: number
          unit_cost: number
          line_total?: never
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          purchase_order_id?: string
          line_number?: number
          product_id?: string
          quantity_ordered?: number
          quantity_received?: number
          unit_cost?: number
          line_total?: never
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "purchase_order_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_order_items_purchase_order_id_fkey"
            columns: ["purchase_order_id"]
            isOneToOne: false
            referencedRelation: "purchase_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      purchase_orders: {
        Row: {
          id: string
          po_number: string
          supplier_id: string
          warehouse_id: string
          status: Database["public"]["Enums"]["purchase_order_status"]
          order_date: string
          expected_delivery_date: string | null
          currency: string
          total_amount: number
          notes: string | null
          created_by: string | null
          submitted_at: string | null
          approved_by: string | null
          approved_at: string | null
          cancelled_by: string | null
          cancelled_at: string | null
          cancel_reason: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          po_number?: string
          supplier_id: string
          warehouse_id: string
          status?: Database["public"]["Enums"]["purchase_order_status"]
          order_date?: string
          expected_delivery_date?: string | null
          currency?: string
          total_amount?: number
          notes?: string | null
          created_by?: string | null
          submitted_at?: string | null
          approved_by?: string | null
          approved_at?: string | null
          cancelled_by?: string | null
          cancelled_at?: string | null
          cancel_reason?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          po_number?: string
          supplier_id?: string
          warehouse_id?: string
          status?: Database["public"]["Enums"]["purchase_order_status"]
          order_date?: string
          expected_delivery_date?: string | null
          currency?: string
          total_amount?: number
          notes?: string | null
          created_by?: string | null
          submitted_at?: string | null
          approved_by?: string | null
          approved_at?: string | null
          cancelled_by?: string | null
          cancelled_at?: string | null
          cancel_reason?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "purchase_orders_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_orders_cancelled_by_fkey"
            columns: ["cancelled_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_orders_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_orders_supplier_id_fkey"
            columns: ["supplier_id"]
            isOneToOne: false
            referencedRelation: "suppliers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "purchase_orders_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      roles: {
        Row: {
          id: number
          code: string
          name: string
          description: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: number
          code: string
          name: string
          description?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: number
          code?: string
          name?: string
          description?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      sales_order_items: {
        Row: {
          id: string
          sales_order_id: string
          line_number: number
          product_id: string
          quantity: number
          quantity_shipped: number
          unit_price: number
          discount_percent: number
          gross_amount: number | null
          discount_amount: number | null
          line_total: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          sales_order_id: string
          line_number: number
          product_id: string
          quantity: number
          quantity_shipped?: number
          unit_price: number
          discount_percent?: number
          gross_amount?: never
          discount_amount?: never
          line_total?: never
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          sales_order_id?: string
          line_number?: number
          product_id?: string
          quantity?: number
          quantity_shipped?: number
          unit_price?: number
          discount_percent?: number
          gross_amount?: never
          discount_amount?: never
          line_total?: never
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sales_order_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_order_items_sales_order_id_fkey"
            columns: ["sales_order_id"]
            isOneToOne: false
            referencedRelation: "sales_orders"
            referencedColumns: ["id"]
          },
        ]
      }
      sales_orders: {
        Row: {
          id: string
          so_number: string
          customer_id: string
          warehouse_id: string
          status: Database["public"]["Enums"]["sales_order_status"]
          order_date: string
          requested_delivery_date: string | null
          currency: string
          subtotal: number
          discount_amount: number
          total_amount: number
          notes: string | null
          created_by: string | null
          confirmed_at: string | null
          shipped_by: string | null
          shipped_at: string | null
          completed_at: string | null
          cancelled_by: string | null
          cancelled_at: string | null
          cancel_reason: string | null
          created_at: string
          updated_at: string
          processing_started_at: string | null
          processing_started_by: string | null
          shipment_posted_at: string | null
          shipment_reversed_at: string | null
          shipment_reversed_by: string | null
          shipment_reversal_reason: string | null
        }
        Insert: {
          id?: string
          so_number?: string
          customer_id: string
          warehouse_id: string
          status?: Database["public"]["Enums"]["sales_order_status"]
          order_date?: string
          requested_delivery_date?: string | null
          currency?: string
          subtotal?: number
          discount_amount?: number
          total_amount?: number
          notes?: string | null
          created_by?: string | null
          confirmed_at?: string | null
          shipped_by?: string | null
          shipped_at?: string | null
          completed_at?: string | null
          cancelled_by?: string | null
          cancelled_at?: string | null
          cancel_reason?: string | null
          created_at?: string
          updated_at?: string
          processing_started_at?: string | null
          processing_started_by?: string | null
          shipment_posted_at?: string | null
          shipment_reversed_at?: string | null
          shipment_reversed_by?: string | null
          shipment_reversal_reason?: string | null
        }
        Update: {
          id?: string
          so_number?: string
          customer_id?: string
          warehouse_id?: string
          status?: Database["public"]["Enums"]["sales_order_status"]
          order_date?: string
          requested_delivery_date?: string | null
          currency?: string
          subtotal?: number
          discount_amount?: number
          total_amount?: number
          notes?: string | null
          created_by?: string | null
          confirmed_at?: string | null
          shipped_by?: string | null
          shipped_at?: string | null
          completed_at?: string | null
          cancelled_by?: string | null
          cancelled_at?: string | null
          cancel_reason?: string | null
          created_at?: string
          updated_at?: string
          processing_started_at?: string | null
          processing_started_by?: string | null
          shipment_posted_at?: string | null
          shipment_reversed_at?: string | null
          shipment_reversed_by?: string | null
          shipment_reversal_reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sales_orders_cancelled_by_fkey"
            columns: ["cancelled_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_orders_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_orders_customer_id_fkey"
            columns: ["customer_id"]
            isOneToOne: false
            referencedRelation: "customers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_orders_processing_started_by_fkey"
            columns: ["processing_started_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_orders_shipment_reversed_by_fkey"
            columns: ["shipment_reversed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_orders_shipped_by_fkey"
            columns: ["shipped_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "sales_orders_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      stock_movements: {
        Row: {
          id: string
          movement_number: string
          movement_type: Database["public"]["Enums"]["movement_type"]
          direction: number
          product_id: string
          warehouse_id: string
          quantity: number
          quantity_change: number | null
          quantity_before: number
          quantity_after: number
          unit_cost: number
          reference_type: string | null
          reference_id: string | null
          reference_number: string | null
          reversal_of_id: string | null
          reason: string | null
          notes: string | null
          performed_by: string | null
          movement_date: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          movement_number?: string
          movement_type: Database["public"]["Enums"]["movement_type"]
          direction: number
          product_id: string
          warehouse_id: string
          quantity: number
          quantity_change?: never
          quantity_before: number
          quantity_after: number
          unit_cost?: number
          reference_type?: string | null
          reference_id?: string | null
          reference_number?: string | null
          reversal_of_id?: string | null
          reason?: string | null
          notes?: string | null
          performed_by?: string | null
          movement_date?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          movement_number?: string
          movement_type?: Database["public"]["Enums"]["movement_type"]
          direction?: number
          product_id?: string
          warehouse_id?: string
          quantity?: number
          quantity_change?: never
          quantity_before?: number
          quantity_after?: number
          unit_cost?: number
          reference_type?: string | null
          reference_id?: string | null
          reference_number?: string | null
          reversal_of_id?: string | null
          reason?: string | null
          notes?: string | null
          performed_by?: string | null
          movement_date?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "stock_movements_performed_by_fkey"
            columns: ["performed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_movements_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_movements_reversal_of_id_fkey"
            columns: ["reversal_of_id"]
            isOneToOne: true
            referencedRelation: "stock_movements"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_movements_warehouse_id_fkey"
            columns: ["warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      stock_transfer_items: {
        Row: {
          id: string
          stock_transfer_id: string
          product_id: string
          quantity: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          stock_transfer_id: string
          product_id: string
          quantity: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          stock_transfer_id?: string
          product_id?: string
          quantity?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "stock_transfer_items_product_id_fkey"
            columns: ["product_id"]
            isOneToOne: false
            referencedRelation: "products"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_transfer_items_stock_transfer_id_fkey"
            columns: ["stock_transfer_id"]
            isOneToOne: false
            referencedRelation: "stock_transfers"
            referencedColumns: ["id"]
          },
        ]
      }
      stock_transfers: {
        Row: {
          id: string
          transfer_number: string
          source_warehouse_id: string
          destination_warehouse_id: string
          status: Database["public"]["Enums"]["transfer_status"]
          requested_by: string | null
          requested_at: string
          approved_by: string | null
          approved_at: string | null
          executed_by: string | null
          executed_at: string | null
          cancelled_by: string | null
          cancelled_at: string | null
          cancel_reason: string | null
          notes: string | null
          created_at: string
          updated_at: string
          rejected_by: string | null
          rejected_at: string | null
          rejection_reason: string | null
        }
        Insert: {
          id?: string
          transfer_number?: string
          source_warehouse_id: string
          destination_warehouse_id: string
          status?: Database["public"]["Enums"]["transfer_status"]
          requested_by?: string | null
          requested_at?: string
          approved_by?: string | null
          approved_at?: string | null
          executed_by?: string | null
          executed_at?: string | null
          cancelled_by?: string | null
          cancelled_at?: string | null
          cancel_reason?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          rejected_by?: string | null
          rejected_at?: string | null
          rejection_reason?: string | null
        }
        Update: {
          id?: string
          transfer_number?: string
          source_warehouse_id?: string
          destination_warehouse_id?: string
          status?: Database["public"]["Enums"]["transfer_status"]
          requested_by?: string | null
          requested_at?: string
          approved_by?: string | null
          approved_at?: string | null
          executed_by?: string | null
          executed_at?: string | null
          cancelled_by?: string | null
          cancelled_at?: string | null
          cancel_reason?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
          rejected_by?: string | null
          rejected_at?: string | null
          rejection_reason?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "stock_transfers_approved_by_fkey"
            columns: ["approved_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_transfers_cancelled_by_fkey"
            columns: ["cancelled_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_transfers_destination_warehouse_id_fkey"
            columns: ["destination_warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_transfers_executed_by_fkey"
            columns: ["executed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_transfers_rejected_by_fkey"
            columns: ["rejected_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_transfers_requested_by_fkey"
            columns: ["requested_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stock_transfers_source_warehouse_id_fkey"
            columns: ["source_warehouse_id"]
            isOneToOne: false
            referencedRelation: "warehouses"
            referencedColumns: ["id"]
          },
        ]
      }
      suppliers: {
        Row: {
          id: string
          code: string
          name: string
          contact_name: string | null
          email: string | null
          phone: string | null
          address_line: string | null
          city: string | null
          country: string
          tax_id: string | null
          payment_terms_days: number
          lead_time_days: number
          notes: string | null
          is_active: boolean
          created_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          code: string
          name: string
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          address_line?: string | null
          city?: string | null
          country?: string
          tax_id?: string | null
          payment_terms_days?: number
          lead_time_days?: number
          notes?: string | null
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          code?: string
          name?: string
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          address_line?: string | null
          city?: string | null
          country?: string
          tax_id?: string | null
          payment_terms_days?: number
          lead_time_days?: number
          notes?: string | null
          is_active?: boolean
          created_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "suppliers_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      warehouses: {
        Row: {
          id: string
          code: string
          name: string
          warehouse_type: string
          address_line: string | null
          city: string
          country: string
          phone: string | null
          manager_id: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          code: string
          name: string
          warehouse_type?: string
          address_line?: string | null
          city: string
          country?: string
          phone?: string | null
          manager_id?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          code?: string
          name?: string
          warehouse_type?: string
          address_line?: string | null
          city?: string
          country?: string
          phone?: string | null
          manager_id?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "warehouses_manager_id_fkey"
            columns: ["manager_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      customer_sales_summary: {
        Row: {
          customer_id: string | null
          code: string | null
          name: string | null
          customer_type: string | null
          contact_name: string | null
          email: string | null
          phone: string | null
          city: string | null
          country: string | null
          credit_limit: number | null
          payment_terms_days: number | null
          is_active: boolean | null
          created_at: string | null
          order_count: number | null
          total_sales_value: number | null
          last_order_date: string | null
          open_count: number | null
          open_value: number | null
        }
        Relationships: []
      }
      goods_receipt_overview: {
        Row: {
          id: string | null
          receipt_number: string | null
          purchase_order_id: string | null
          po_number: string | null
          supplier_id: string | null
          supplier_name: string | null
          warehouse_id: string | null
          warehouse_code: string | null
          warehouse_name: string | null
          received_at: string | null
          received_by: string | null
          received_by_name: string | null
          notes: string | null
          line_count: number | null
          total_quantity: number | null
          total_value: number | null
          reversed_at: string | null
          reversed_by_name: string | null
          reversal_reason: string | null
          created_at: string | null
        }
        Relationships: []
      }
      inventory_valuation: {
        Row: {
          inventory_id: string | null
          product_id: string | null
          sku: string | null
          product_name: string | null
          unit_of_measure: string | null
          category_id: string | null
          category_name: string | null
          warehouse_id: string | null
          warehouse_code: string | null
          warehouse_name: string | null
          quantity: number | null
          min_stock_level: number | null
          cost_price: number | null
          inventory_value: number | null
          stock_status: string | null
          product_is_active: boolean | null
          warehouse_is_active: boolean | null
          bin_location: string | null
          last_movement_at: string | null
        }
        Relationships: []
      }
      product_stock_summary: {
        Row: {
          product_id: string | null
          sku: string | null
          name: string | null
          barcode: string | null
          unit_of_measure: string | null
          category_id: string | null
          category_name: string | null
          cost_price: number | null
          sale_price: number | null
          min_stock_level: number | null
          reorder_quantity: number | null
          is_active: boolean | null
          created_at: string | null
          updated_at: string | null
          total_quantity: number | null
          inventory_value: number | null
          warehouse_count: number | null
          stock_status: string | null
        }
        Relationships: []
      }
      purchase_order_overview: {
        Row: {
          id: string | null
          po_number: string | null
          status: Database["public"]["Enums"]["purchase_order_status"] | null
          supplier_id: string | null
          supplier_code: string | null
          supplier_name: string | null
          warehouse_id: string | null
          warehouse_code: string | null
          warehouse_name: string | null
          order_date: string | null
          expected_delivery_date: string | null
          currency: string | null
          total_amount: number | null
          notes: string | null
          line_count: number | null
          quantity_ordered: number | null
          quantity_received: number | null
          received_value: number | null
          outstanding_value: number | null
          created_by: string | null
          created_by_name: string | null
          submitted_at: string | null
          approved_by: string | null
          approved_by_name: string | null
          approved_at: string | null
          cancelled_at: string | null
          cancel_reason: string | null
          last_received_at: string | null
          created_at: string | null
          updated_at: string | null
        }
        Relationships: []
      }
      sales_order_overview: {
        Row: {
          id: string | null
          so_number: string | null
          status: Database["public"]["Enums"]["sales_order_status"] | null
          customer_id: string | null
          customer_code: string | null
          customer_name: string | null
          customer_type: string | null
          warehouse_id: string | null
          warehouse_code: string | null
          warehouse_name: string | null
          order_date: string | null
          requested_delivery_date: string | null
          currency: string | null
          subtotal: number | null
          discount_amount: number | null
          total_amount: number | null
          notes: string | null
          line_count: number | null
          quantity: number | null
          quantity_shipped: number | null
          created_by: string | null
          created_by_name: string | null
          confirmed_at: string | null
          processing_started_at: string | null
          shipped_at: string | null
          shipped_by_name: string | null
          completed_at: string | null
          cancelled_at: string | null
          cancel_reason: string | null
          shipment_reversed_at: string | null
          shipment_reversal_reason: string | null
          created_at: string | null
          updated_at: string | null
        }
        Relationships: []
      }
      stock_movement_ledger: {
        Row: {
          id: string | null
          movement_number: string | null
          movement_type: Database["public"]["Enums"]["movement_type"] | null
          direction: number | null
          quantity: number | null
          quantity_change: number | null
          quantity_before: number | null
          quantity_after: number | null
          unit_cost: number | null
          movement_value: number | null
          product_id: string | null
          sku: string | null
          product_name: string | null
          warehouse_id: string | null
          warehouse_code: string | null
          warehouse_name: string | null
          reference_type: string | null
          reference_id: string | null
          reference_number: string | null
          reversal_of_id: string | null
          reversal_of_number: string | null
          reversed_by_id: string | null
          reversed_by_number: string | null
          reason: string | null
          notes: string | null
          performed_by: string | null
          performed_by_name: string | null
          movement_date: string | null
          created_at: string | null
        }
        Relationships: []
      }
      stock_transfer_overview: {
        Row: {
          id: string | null
          transfer_number: string | null
          status: Database["public"]["Enums"]["transfer_status"] | null
          source_warehouse_id: string | null
          source_code: string | null
          source_name: string | null
          destination_warehouse_id: string | null
          destination_code: string | null
          destination_name: string | null
          notes: string | null
          line_count: number | null
          total_quantity: number | null
          total_value: number | null
          requested_by: string | null
          requested_by_name: string | null
          requested_at: string | null
          approved_by_name: string | null
          approved_at: string | null
          executed_by_name: string | null
          executed_at: string | null
          rejected_by_name: string | null
          rejected_at: string | null
          rejection_reason: string | null
          cancelled_by_name: string | null
          cancelled_at: string | null
          cancel_reason: string | null
          created_at: string | null
        }
        Relationships: []
      }
      supplier_purchase_summary: {
        Row: {
          supplier_id: string | null
          code: string | null
          name: string | null
          contact_name: string | null
          email: string | null
          phone: string | null
          city: string | null
          country: string | null
          payment_terms_days: number | null
          lead_time_days: number | null
          is_active: boolean | null
          created_at: string | null
          order_count: number | null
          total_purchase_value: number | null
          received_value: number | null
          last_order_date: string | null
          outstanding_count: number | null
          outstanding_value: number | null
        }
        Relationships: []
      }
      warehouse_stock_summary: {
        Row: {
          warehouse_id: string | null
          code: string | null
          name: string | null
          warehouse_type: string | null
          city: string | null
          is_active: boolean | null
          manager_id: string | null
          manager_name: string | null
          product_count: number | null
          total_quantity: number | null
          inventory_value: number | null
          low_stock_count: number | null
          out_of_stock_count: number | null
        }
        Relationships: []
      }
    }
    Functions: {
      approve_purchase_order: {
        Args: {
          p_po_id: string
        }
        Returns: Database["public"]["Tables"]["purchase_orders"]["Row"]
      }
      approve_stock_transfer: {
        Args: {
          p_transfer_id: string
        }
        Returns: Database["public"]["Tables"]["stock_transfers"]["Row"]
      }
      cancel_purchase_order: {
        Args: {
          p_po_id: string
          p_reason: string
        }
        Returns: Database["public"]["Tables"]["purchase_orders"]["Row"]
      }
      cancel_sales_order: {
        Args: {
          p_so_id: string
          p_reason: string
        }
        Returns: Database["public"]["Tables"]["sales_orders"]["Row"]
      }
      cancel_stock_transfer: {
        Args: {
          p_transfer_id: string
          p_reason: string
        }
        Returns: Database["public"]["Tables"]["stock_transfers"]["Row"]
      }
      complete_sales_order: {
        Args: {
          p_so_id: string
        }
        Returns: Database["public"]["Tables"]["sales_orders"]["Row"]
      }
      confirm_sales_order: {
        Args: {
          p_so_id: string
        }
        Returns: Database["public"]["Tables"]["sales_orders"]["Row"]
      }
      create_purchase_order: {
        Args: {
          p_supplier_id: string
          p_warehouse_id: string
          p_items: Json
          p_order_date?: string
          p_expected_delivery_date?: string
          p_notes?: string
        }
        Returns: Database["public"]["Tables"]["purchase_orders"]["Row"]
      }
      create_sales_order: {
        Args: {
          p_customer_id: string
          p_warehouse_id: string
          p_items: Json
          p_order_date?: string
          p_requested_delivery_date?: string
          p_notes?: string
        }
        Returns: Database["public"]["Tables"]["sales_orders"]["Row"]
      }
      create_stock_movement: {
        Args: {
          p_product_id: string
          p_warehouse_id: string
          p_movement_type: Database["public"]["Enums"]["movement_type"]
          p_quantity: number
          p_reference_type?: string
          p_reference_id?: string
          p_reference_number?: string
          p_reason?: string
          p_notes?: string
          p_movement_date?: string
          p_direction?: number
          p_unit_cost?: number
        }
        Returns: Database["public"]["Tables"]["stock_movements"]["Row"]
      }
      execute_stock_transfer: {
        Args: {
          p_transfer_id: string
        }
        Returns: Database["public"]["Tables"]["stock_transfers"]["Row"]
      }
      inventory_totals: {
        Args: {
          p_warehouse_id?: string
          p_category_id?: string
          p_stock_status?: string
          p_search?: string
        }
        Returns: {
          line_count: number
          total_quantity: number
          inventory_value: number
          low_stock_count: number
          out_of_stock_count: number
        }[]
      }
      receive_goods: {
        Args: {
          p_po_id: string
          p_items: Json
          p_notes?: string
          p_received_at?: string
        }
        Returns: Database["public"]["Tables"]["goods_receipts"]["Row"]
      }
      reject_stock_transfer: {
        Args: {
          p_transfer_id: string
          p_reason: string
        }
        Returns: Database["public"]["Tables"]["stock_transfers"]["Row"]
      }
      request_stock_transfer: {
        Args: {
          p_source_warehouse_id: string
          p_destination_warehouse_id: string
          p_items: Json
          p_notes?: string
        }
        Returns: Database["public"]["Tables"]["stock_transfers"]["Row"]
      }
      reverse_goods_receipt: {
        Args: {
          p_goods_receipt_id: string
          p_reason: string
        }
        Returns: Database["public"]["Tables"]["goods_receipts"]["Row"]
      }
      reverse_sales_order_shipment: {
        Args: {
          p_so_id: string
          p_reason: string
        }
        Returns: Database["public"]["Tables"]["sales_orders"]["Row"]
      }
      reverse_stock_movement: {
        Args: {
          p_movement_id: string
          p_reason: string
        }
        Returns: Database["public"]["Tables"]["stock_movements"]["Row"]
      }
      ship_sales_order: {
        Args: {
          p_so_id: string
          p_shipped_at?: string
        }
        Returns: Database["public"]["Tables"]["sales_orders"]["Row"]
      }
      start_processing_sales_order: {
        Args: {
          p_so_id: string
        }
        Returns: Database["public"]["Tables"]["sales_orders"]["Row"]
      }
      submit_purchase_order: {
        Args: {
          p_po_id: string
        }
        Returns: Database["public"]["Tables"]["purchase_orders"]["Row"]
      }
      update_purchase_order: {
        Args: {
          p_po_id: string
          p_supplier_id: string
          p_warehouse_id: string
          p_items: Json
          p_order_date?: string
          p_expected_delivery_date?: string
          p_notes?: string
        }
        Returns: Database["public"]["Tables"]["purchase_orders"]["Row"]
      }
      update_sales_order: {
        Args: {
          p_so_id: string
          p_customer_id: string
          p_warehouse_id: string
          p_items: Json
          p_order_date?: string
          p_requested_delivery_date?: string
          p_notes?: string
        }
        Returns: Database["public"]["Tables"]["sales_orders"]["Row"]
      }
    }
    Enums: {
      movement_type: "PURCHASE_RECEIPT" | "SALE" | "TRANSFER_IN" | "TRANSFER_OUT" | "ADJUSTMENT_IN" | "ADJUSTMENT_OUT" | "RETURN"
      purchase_order_status: "DRAFT" | "SUBMITTED" | "APPROVED" | "PARTIALLY_RECEIVED" | "RECEIVED" | "CANCELLED"
      sales_order_status: "DRAFT" | "CONFIRMED" | "PROCESSING" | "SHIPPED" | "COMPLETED" | "CANCELLED"
      transfer_status: "REQUESTED" | "APPROVED" | "COMPLETED" | "REJECTED" | "CANCELLED"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database["public"]

export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"]
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"]
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"]
export type Views<T extends keyof PublicSchema["Views"]> = PublicSchema["Views"][T]["Row"]
export type Enums<T extends keyof PublicSchema["Enums"]> = PublicSchema["Enums"][T]

export const Constants = {
  public: {
    Enums: {
      movement_type: ["PURCHASE_RECEIPT", "SALE", "TRANSFER_IN", "TRANSFER_OUT", "ADJUSTMENT_IN", "ADJUSTMENT_OUT", "RETURN"],
      purchase_order_status: ["DRAFT", "SUBMITTED", "APPROVED", "PARTIALLY_RECEIVED", "RECEIVED", "CANCELLED"],
      sales_order_status: ["DRAFT", "CONFIRMED", "PROCESSING", "SHIPPED", "COMPLETED", "CANCELLED"],
      transfer_status: ["REQUESTED", "APPROVED", "COMPLETED", "REJECTED", "CANCELLED"],
    },
  },
} as const
